name: Quality Check Bot

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
    
      - name: Navigate to the correct directory
        working-directory: ./thermotrack-mini
        run: pwd
    
      - name: Install dependencies
        working-directory: ./thermotrack-mini
        run: npm install
    
      - name: Run Lint
        working-directory: ./thermotrack-mini
        run: npm run lint
    
      - name: Build App
        working-directory: ./thermotrack-mini
        run: npm run build
      - name: List files after lint
        working-directory: ./thermotrack-mini
        run: ls -la
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Commit lint report
        working-directory: ./thermotrack-mini
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "BOT1"
          git config user.email "qualitycheckbot@users.noreply.github.com"
          git add lint-report.json
          git commit -m "Add lint report [bot]"
          git push origin main
